version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile81
    image: web_crawler
    container_name: web_crawler_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: web_crawler_webserver
    restart: unless-stopped
    tty: true
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
    ports:
      - "2000:80"
      - "2020:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: web_crawler_db
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: web_crawler_local
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
